name: 提交检查
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_html:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 将文档编译成 HTML
      run: |
        git checkout -b _checkout
        git submodule update --init --depth=1
        pushd taichi
        git checkout -b _checkout
        popd
        make all
        make html
